name: Release builds

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --features=clap
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: flour-linux
        path: ${{runner.workspace}}/flour/target/release/flour
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --features=clap
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: flour-windows
        path: ${{runner.workspace}}/flour/target/release/flour.exe
  macos:
    name: Mac
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --features=clap
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: flour-mac
        path: ${{runner.workspace}}/flour/target/release/flour